// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dns.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DNSStartReq struct {
	Config               string   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSStartReq) Reset()         { *m = DNSStartReq{} }
func (m *DNSStartReq) String() string { return proto.CompactTextString(m) }
func (*DNSStartReq) ProtoMessage()    {}
func (*DNSStartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{0}
}

func (m *DNSStartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSStartReq.Unmarshal(m, b)
}
func (m *DNSStartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSStartReq.Marshal(b, m, deterministic)
}
func (m *DNSStartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSStartReq.Merge(m, src)
}
func (m *DNSStartReq) XXX_Size() int {
	return xxx_messageInfo_DNSStartReq.Size(m)
}
func (m *DNSStartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSStartReq.DiscardUnknown(m)
}

var xxx_messageInfo_DNSStartReq proto.InternalMessageInfo

func (m *DNSStartReq) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type DNSStopReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSStopReq) Reset()         { *m = DNSStopReq{} }
func (m *DNSStopReq) String() string { return proto.CompactTextString(m) }
func (*DNSStopReq) ProtoMessage()    {}
func (*DNSStopReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{1}
}

func (m *DNSStopReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSStopReq.Unmarshal(m, b)
}
func (m *DNSStopReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSStopReq.Marshal(b, m, deterministic)
}
func (m *DNSStopReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSStopReq.Merge(m, src)
}
func (m *DNSStopReq) XXX_Size() int {
	return xxx_messageInfo_DNSStopReq.Size(m)
}
func (m *DNSStopReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSStopReq.DiscardUnknown(m)
}

var xxx_messageInfo_DNSStopReq proto.InternalMessageInfo

type CreateACLReq struct {
	ACLName              string   `protobuf:"bytes,1,opt,name=aCLName,proto3" json:"aCLName,omitempty"`
	ACLID                string   `protobuf:"bytes,2,opt,name=aCLID,proto3" json:"aCLID,omitempty"`
	IpList               []string `protobuf:"bytes,3,rep,name=ipList,proto3" json:"ipList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateACLReq) Reset()         { *m = CreateACLReq{} }
func (m *CreateACLReq) String() string { return proto.CompactTextString(m) }
func (*CreateACLReq) ProtoMessage()    {}
func (*CreateACLReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{2}
}

func (m *CreateACLReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateACLReq.Unmarshal(m, b)
}
func (m *CreateACLReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateACLReq.Marshal(b, m, deterministic)
}
func (m *CreateACLReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateACLReq.Merge(m, src)
}
func (m *CreateACLReq) XXX_Size() int {
	return xxx_messageInfo_CreateACLReq.Size(m)
}
func (m *CreateACLReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateACLReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateACLReq proto.InternalMessageInfo

func (m *CreateACLReq) GetACLName() string {
	if m != nil {
		return m.ACLName
	}
	return ""
}

func (m *CreateACLReq) GetACLID() string {
	if m != nil {
		return m.ACLID
	}
	return ""
}

func (m *CreateACLReq) GetIpList() []string {
	if m != nil {
		return m.IpList
	}
	return nil
}

type DeleteACLReq struct {
	ACLID                string   `protobuf:"bytes,1,opt,name=aCLID,proto3" json:"aCLID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteACLReq) Reset()         { *m = DeleteACLReq{} }
func (m *DeleteACLReq) String() string { return proto.CompactTextString(m) }
func (*DeleteACLReq) ProtoMessage()    {}
func (*DeleteACLReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{3}
}

func (m *DeleteACLReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteACLReq.Unmarshal(m, b)
}
func (m *DeleteACLReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteACLReq.Marshal(b, m, deterministic)
}
func (m *DeleteACLReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteACLReq.Merge(m, src)
}
func (m *DeleteACLReq) XXX_Size() int {
	return xxx_messageInfo_DeleteACLReq.Size(m)
}
func (m *DeleteACLReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteACLReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteACLReq proto.InternalMessageInfo

func (m *DeleteACLReq) GetACLID() string {
	if m != nil {
		return m.ACLID
	}
	return ""
}

type CreateViewReq struct {
	ViewName             string   `protobuf:"bytes,1,opt,name=viewName,proto3" json:"viewName,omitempty"`
	ViewID               string   `protobuf:"bytes,2,opt,name=viewID,proto3" json:"viewID,omitempty"`
	Priority             int32    `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	ACLID                string   `protobuf:"bytes,4,opt,name=aCLID,proto3" json:"aCLID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateViewReq) Reset()         { *m = CreateViewReq{} }
func (m *CreateViewReq) String() string { return proto.CompactTextString(m) }
func (*CreateViewReq) ProtoMessage()    {}
func (*CreateViewReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{4}
}

func (m *CreateViewReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateViewReq.Unmarshal(m, b)
}
func (m *CreateViewReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateViewReq.Marshal(b, m, deterministic)
}
func (m *CreateViewReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateViewReq.Merge(m, src)
}
func (m *CreateViewReq) XXX_Size() int {
	return xxx_messageInfo_CreateViewReq.Size(m)
}
func (m *CreateViewReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateViewReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateViewReq proto.InternalMessageInfo

func (m *CreateViewReq) GetViewName() string {
	if m != nil {
		return m.ViewName
	}
	return ""
}

func (m *CreateViewReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *CreateViewReq) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *CreateViewReq) GetACLID() string {
	if m != nil {
		return m.ACLID
	}
	return ""
}

type UpdateViewReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	ACLID                string   `protobuf:"bytes,3,opt,name=aCLID,proto3" json:"aCLID,omitempty"`
	DeleteIPList         []string `protobuf:"bytes,4,rep,name=deleteIPList,proto3" json:"deleteIPList,omitempty"`
	NewIPList            []string `protobuf:"bytes,5,rep,name=newIPList,proto3" json:"newIPList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateViewReq) Reset()         { *m = UpdateViewReq{} }
func (m *UpdateViewReq) String() string { return proto.CompactTextString(m) }
func (*UpdateViewReq) ProtoMessage()    {}
func (*UpdateViewReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{5}
}

func (m *UpdateViewReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateViewReq.Unmarshal(m, b)
}
func (m *UpdateViewReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateViewReq.Marshal(b, m, deterministic)
}
func (m *UpdateViewReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateViewReq.Merge(m, src)
}
func (m *UpdateViewReq) XXX_Size() int {
	return xxx_messageInfo_UpdateViewReq.Size(m)
}
func (m *UpdateViewReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateViewReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateViewReq proto.InternalMessageInfo

func (m *UpdateViewReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *UpdateViewReq) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *UpdateViewReq) GetACLID() string {
	if m != nil {
		return m.ACLID
	}
	return ""
}

func (m *UpdateViewReq) GetDeleteIPList() []string {
	if m != nil {
		return m.DeleteIPList
	}
	return nil
}

func (m *UpdateViewReq) GetNewIPList() []string {
	if m != nil {
		return m.NewIPList
	}
	return nil
}

type DeleteViewReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteViewReq) Reset()         { *m = DeleteViewReq{} }
func (m *DeleteViewReq) String() string { return proto.CompactTextString(m) }
func (*DeleteViewReq) ProtoMessage()    {}
func (*DeleteViewReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{6}
}

func (m *DeleteViewReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteViewReq.Unmarshal(m, b)
}
func (m *DeleteViewReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteViewReq.Marshal(b, m, deterministic)
}
func (m *DeleteViewReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteViewReq.Merge(m, src)
}
func (m *DeleteViewReq) XXX_Size() int {
	return xxx_messageInfo_DeleteViewReq.Size(m)
}
func (m *DeleteViewReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteViewReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteViewReq proto.InternalMessageInfo

func (m *DeleteViewReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

type CreateZoneReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ZoneID               string   `protobuf:"bytes,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	ZoneName             string   `protobuf:"bytes,3,opt,name=zoneName,proto3" json:"zoneName,omitempty"`
	ZoneFileName         string   `protobuf:"bytes,4,opt,name=zoneFileName,proto3" json:"zoneFileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateZoneReq) Reset()         { *m = CreateZoneReq{} }
func (m *CreateZoneReq) String() string { return proto.CompactTextString(m) }
func (*CreateZoneReq) ProtoMessage()    {}
func (*CreateZoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{7}
}

func (m *CreateZoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateZoneReq.Unmarshal(m, b)
}
func (m *CreateZoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateZoneReq.Marshal(b, m, deterministic)
}
func (m *CreateZoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateZoneReq.Merge(m, src)
}
func (m *CreateZoneReq) XXX_Size() int {
	return xxx_messageInfo_CreateZoneReq.Size(m)
}
func (m *CreateZoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateZoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateZoneReq proto.InternalMessageInfo

func (m *CreateZoneReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *CreateZoneReq) GetZoneID() string {
	if m != nil {
		return m.ZoneID
	}
	return ""
}

func (m *CreateZoneReq) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *CreateZoneReq) GetZoneFileName() string {
	if m != nil {
		return m.ZoneFileName
	}
	return ""
}

type DeleteZoneReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ZoneID               string   `protobuf:"bytes,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteZoneReq) Reset()         { *m = DeleteZoneReq{} }
func (m *DeleteZoneReq) String() string { return proto.CompactTextString(m) }
func (*DeleteZoneReq) ProtoMessage()    {}
func (*DeleteZoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{8}
}

func (m *DeleteZoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteZoneReq.Unmarshal(m, b)
}
func (m *DeleteZoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteZoneReq.Marshal(b, m, deterministic)
}
func (m *DeleteZoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteZoneReq.Merge(m, src)
}
func (m *DeleteZoneReq) XXX_Size() int {
	return xxx_messageInfo_DeleteZoneReq.Size(m)
}
func (m *DeleteZoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteZoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteZoneReq proto.InternalMessageInfo

func (m *DeleteZoneReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *DeleteZoneReq) GetZoneID() string {
	if m != nil {
		return m.ZoneID
	}
	return ""
}

type CreateRRReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ZoneID               string   `protobuf:"bytes,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	RrID                 string   `protobuf:"bytes,3,opt,name=rrID,proto3" json:"rrID,omitempty"`
	Rrdata               string   `protobuf:"bytes,4,opt,name=rrdata,proto3" json:"rrdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRRReq) Reset()         { *m = CreateRRReq{} }
func (m *CreateRRReq) String() string { return proto.CompactTextString(m) }
func (*CreateRRReq) ProtoMessage()    {}
func (*CreateRRReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{9}
}

func (m *CreateRRReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRRReq.Unmarshal(m, b)
}
func (m *CreateRRReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRRReq.Marshal(b, m, deterministic)
}
func (m *CreateRRReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRRReq.Merge(m, src)
}
func (m *CreateRRReq) XXX_Size() int {
	return xxx_messageInfo_CreateRRReq.Size(m)
}
func (m *CreateRRReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRRReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRRReq proto.InternalMessageInfo

func (m *CreateRRReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *CreateRRReq) GetZoneID() string {
	if m != nil {
		return m.ZoneID
	}
	return ""
}

func (m *CreateRRReq) GetRrID() string {
	if m != nil {
		return m.RrID
	}
	return ""
}

func (m *CreateRRReq) GetRrdata() string {
	if m != nil {
		return m.Rrdata
	}
	return ""
}

type UpdateRRReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ZoneID               string   `protobuf:"bytes,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	RrID                 string   `protobuf:"bytes,3,opt,name=rrID,proto3" json:"rrID,omitempty"`
	NewrrData            string   `protobuf:"bytes,4,opt,name=newrrData,proto3" json:"newrrData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRRReq) Reset()         { *m = UpdateRRReq{} }
func (m *UpdateRRReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRRReq) ProtoMessage()    {}
func (*UpdateRRReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{10}
}

func (m *UpdateRRReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRRReq.Unmarshal(m, b)
}
func (m *UpdateRRReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRRReq.Marshal(b, m, deterministic)
}
func (m *UpdateRRReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRRReq.Merge(m, src)
}
func (m *UpdateRRReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRRReq.Size(m)
}
func (m *UpdateRRReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRRReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRRReq proto.InternalMessageInfo

func (m *UpdateRRReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *UpdateRRReq) GetZoneID() string {
	if m != nil {
		return m.ZoneID
	}
	return ""
}

func (m *UpdateRRReq) GetRrID() string {
	if m != nil {
		return m.RrID
	}
	return ""
}

func (m *UpdateRRReq) GetNewrrData() string {
	if m != nil {
		return m.NewrrData
	}
	return ""
}

type DeleteRRReq struct {
	ViewID               string   `protobuf:"bytes,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ZoneID               string   `protobuf:"bytes,2,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	RrID                 string   `protobuf:"bytes,3,opt,name=rrID,proto3" json:"rrID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRRReq) Reset()         { *m = DeleteRRReq{} }
func (m *DeleteRRReq) String() string { return proto.CompactTextString(m) }
func (*DeleteRRReq) ProtoMessage()    {}
func (*DeleteRRReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{11}
}

func (m *DeleteRRReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRRReq.Unmarshal(m, b)
}
func (m *DeleteRRReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRRReq.Marshal(b, m, deterministic)
}
func (m *DeleteRRReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRRReq.Merge(m, src)
}
func (m *DeleteRRReq) XXX_Size() int {
	return xxx_messageInfo_DeleteRRReq.Size(m)
}
func (m *DeleteRRReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRRReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRRReq proto.InternalMessageInfo

func (m *DeleteRRReq) GetViewID() string {
	if m != nil {
		return m.ViewID
	}
	return ""
}

func (m *DeleteRRReq) GetZoneID() string {
	if m != nil {
		return m.ZoneID
	}
	return ""
}

func (m *DeleteRRReq) GetRrID() string {
	if m != nil {
		return m.RrID
	}
	return ""
}

func init() {
	proto.RegisterType((*DNSStartReq)(nil), "pb.DNSStartReq")
	proto.RegisterType((*DNSStopReq)(nil), "pb.DNSStopReq")
	proto.RegisterType((*CreateACLReq)(nil), "pb.CreateACLReq")
	proto.RegisterType((*DeleteACLReq)(nil), "pb.DeleteACLReq")
	proto.RegisterType((*CreateViewReq)(nil), "pb.CreateViewReq")
	proto.RegisterType((*UpdateViewReq)(nil), "pb.UpdateViewReq")
	proto.RegisterType((*DeleteViewReq)(nil), "pb.DeleteViewReq")
	proto.RegisterType((*CreateZoneReq)(nil), "pb.CreateZoneReq")
	proto.RegisterType((*DeleteZoneReq)(nil), "pb.DeleteZoneReq")
	proto.RegisterType((*CreateRRReq)(nil), "pb.CreateRRReq")
	proto.RegisterType((*UpdateRRReq)(nil), "pb.UpdateRRReq")
	proto.RegisterType((*DeleteRRReq)(nil), "pb.DeleteRRReq")
}

func init() { proto.RegisterFile("dns.proto", fileDescriptor_638ff8d8aaf3d8ae) }

var fileDescriptor_638ff8d8aaf3d8ae = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0x4d, 0x5b, 0xed, 0x24, 0xbd, 0x04, 0x29, 0x41, 0x3c, 0x94, 0x45, 0xb1, 0x27, 0x2f,
	0x3e, 0x80, 0x48, 0x82, 0x50, 0x08, 0x45, 0x53, 0xec, 0xc1, 0xdb, 0xd6, 0xac, 0xb2, 0x50, 0xb3,
	0xe9, 0x76, 0xb5, 0xe8, 0xc5, 0x07, 0xf1, 0x65, 0x65, 0x77, 0xd2, 0xdd, 0xf4, 0x50, 0x85, 0xd2,
	0xdb, 0x7c, 0x93, 0x99, 0xf9, 0x7e, 0x96, 0x40, 0xaf, 0x28, 0x57, 0x57, 0x95, 0x14, 0x4a, 0x44,
	0xad, 0x6a, 0x4e, 0x2e, 0x20, 0x48, 0x27, 0xd3, 0xa9, 0xa2, 0x52, 0xe5, 0x6c, 0x19, 0x0d, 0xa0,
	0xfb, 0x2c, 0xca, 0x17, 0xfe, 0x1a, 0x7b, 0x43, 0x6f, 0xd4, 0xcb, 0x6b, 0x44, 0x42, 0x00, 0x33,
	0x26, 0xaa, 0x9c, 0x2d, 0xc9, 0x0c, 0xc2, 0x44, 0x32, 0xaa, 0xd8, 0x6d, 0x92, 0xe9, 0xad, 0x18,
	0x8e, 0x68, 0x92, 0x4d, 0xe8, 0x1b, 0xab, 0xd7, 0x36, 0x30, 0x3a, 0x81, 0x0e, 0x4d, 0xb2, 0x71,
	0x1a, 0xb7, 0x4c, 0x1f, 0x81, 0x66, 0xe1, 0x55, 0xc6, 0x57, 0x2a, 0xf6, 0x87, 0xbe, 0x66, 0x41,
	0x44, 0xce, 0x21, 0x4c, 0xd9, 0x82, 0xd9, 0xbb, 0x76, 0xdb, 0x6b, 0x6c, 0x93, 0x77, 0xe8, 0x23,
	0xfb, 0x8c, 0xb3, 0xb5, 0x1e, 0x3b, 0x85, 0xe3, 0x0f, 0xce, 0xd6, 0x0d, 0x7e, 0x8b, 0x35, 0x95,
	0xae, 0xad, 0x82, 0x1a, 0xe9, 0x9d, 0x4a, 0x72, 0x21, 0xb9, 0xfa, 0x8c, 0xfd, 0xa1, 0x37, 0xea,
	0xe4, 0x16, 0x3b, 0xda, 0x76, 0x93, 0xf6, 0xc7, 0x83, 0xfe, 0x63, 0x55, 0x34, 0x78, 0xdd, 0x6d,
	0x6f, 0xe7, 0xed, 0xd6, 0xae, 0xdb, 0x7e, 0x33, 0x10, 0x02, 0x61, 0x61, 0x8c, 0x8f, 0xef, 0x4d,
	0x2c, 0x6d, 0x13, 0xcb, 0x56, 0x2f, 0x3a, 0x83, 0x5e, 0xc9, 0xd6, 0xf5, 0x40, 0xc7, 0x0c, 0xb8,
	0x06, 0xb9, 0x84, 0x3e, 0x46, 0xf7, 0x8f, 0x38, 0xf2, 0xbd, 0x49, 0xef, 0x49, 0x94, 0xec, 0x2f,
	0x17, 0x03, 0xe8, 0x7e, 0x89, 0x92, 0xb9, 0xe4, 0x10, 0x69, 0x77, 0xba, 0x32, 0x69, 0xa3, 0x09,
	0x8b, 0xb5, 0x0f, 0x5d, 0xdf, 0xf1, 0x05, 0x7e, 0xc7, 0x00, 0xb7, 0x7a, 0xe4, 0x66, 0xa3, 0x74,
	0x4f, 0x01, 0x84, 0x43, 0x80, 0x0e, 0xf2, 0x7c, 0x1f, 0xfd, 0x11, 0xb4, 0xa5, 0xb4, 0x0f, 0x60,
	0x6a, 0x3d, 0x2b, 0x65, 0x41, 0x15, 0xad, 0x15, 0xd7, 0x88, 0x08, 0x08, 0xf0, 0xc9, 0x0f, 0x47,
	0x85, 0xcf, 0x28, 0x65, 0xea, 0xd8, 0x5c, 0x83, 0x3c, 0x40, 0x80, 0xe1, 0x1c, 0x8c, 0x70, 0xde,
	0x35, 0x3f, 0xfb, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x7c, 0x54, 0x3d, 0xf9, 0x03,
	0x00, 0x00,
}
